apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
spec:
  type: ${{ values.type | dump }}
  owner: ${{ values.email | dump }}
  system: ${{ values.business_unit | dump }}
  lifecycle: ${{ values.lifecycle | dump }}
